<div class="container">
    
    <h1>User List</h1>
    <form class="form-inline" action="<?php echo $this->basePath()?>/foo/var/users" method="POST">
            <div class="form-group">
                <label>Email</label>
                <input type="text" class="form-control" id="txtEmail" name="email" placeholder="example@hotmail.com" value="<?php echo !empty($post['email']) ? $post['email']:'';?>">
            </div>
            <div class="col-lg-offset-1 form-group">
                <label>Gender</label>
                <label class="checkbox-inline">
                    <input type="checkbox" id="checkboxMale" value="female" name="gender" <?php echo (!empty($post['gender']) && $post['gender'] == "female") ? 'checked': '';?>> Male
                </label>
                <label class="checkbox-inline">
                    <input type="checkbox" id="checkboxFemale" value="male" name="gender" <?php echo (!empty($post['gender']) && $post['gender'] =="male") ? 'checked': '';?>> Female
                </label>
            </div>
            <div class="col-lg-offset-1 form-group">
                <label>Age</label>
                <select class="form-control" name="age">
                    <option value="">Seleccione su edad</option>
                <?php if (!empty($post['age'])) :?>
                    <?php for ($i = 1; $i < 50; $i++) :?>
                    <option value="<?php echo $i;?>" <?php echo ($post['age'] == $i) ? 'selected="selected"' : '';?>><?php echo $i;?></option>
                    <?php endfor;?>
                <?php else : ?>
                    <?php for ($i = 1; $i < 50; $i++) :?>
                    <option value="<?php echo $i;?>"><?php echo $i;?></option>
                    <?php endfor;?>
                <?php endif;?>
                    
                </select>
            </div>
            
            <div class="col-lg-offset-1 form-group">
                <button type="submit" class="btn btn-primary btn-lg">Filter</button>
            </div>
        </form>
    <br>
    <table class="table table-bordered">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Gender</th>
            <th>Age</th>
        </thead>
        <tbody>
            <?php if ($usuarios) :?>
            <?php foreach ($usuarios as $usuario) :?>
                <tr>
                    <td><a href="<?php echo $this->basePath()?>/foo/var/user-detail/<?php echo $usuario['id'];?>"><?php echo $usuario['id']?></a></td>
                    <td><?php echo $usuario['firstName'] . " " . $usuario['lastName']?></td>
                    <td><?php echo $usuario['email']?></td>
                    <td><?php echo $usuario['gender']?></td>
                    <td><?php echo $usuario['age']?></td>
                </tr>
            <?php endforeach;?>
            <?php else :?>
                <h3>No se encontraron resultados! , por favor realice otra búsqueda</h3>
            <?php endif;?>
        </tbody>
    </table>
    
    <ul id="pagination-demo" class="pagination-sm"></ul>
    
       
</div>

<script type="text/javascript">
$('#pagination-demo').twbsPagination({
    totalPages: <?php echo $cantPages?>,
    visiblePages: 3,
    href: '/foo/var/users/{{number}}',
    onPageClick: function (event, page) {
        $('#page-content').text('Page ' + page);
    }
});    
</script>