<div class="container">
    
    <h1>User List</h1>
    <br>
    <form class="form-inline" action="<?php echo $this->basePath()?>/foo/var/users" method="POST">

        <div class="form-group col-sm-4">
            <label class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input
                    type="text"
                    class="form-control"
                    id="txtEmail"
                    name="email"
                    placeholder="example@my-domain.com"
                    value="<?php echo !empty($post['email']) ? $post['email']:'';?>">
            </div>
        </div>

        <div class="col-sm-3">
            <label class="control-label">Gender &nbsp;</label>
            <label class="checkbox-inline">
                <input
                    type="checkbox"
                    id="checkboxMale"
                    value="male"
                    name="gender"
                    <?php echo (!empty($post['gender']) && $post['gender'] == "male") ? 'checked': '';?>> Male
            </label>
            <label class="checkbox-inline">
                <input
                    type="checkbox"
                    id="checkboxFemale"
                    value="female"
                    name="gender"
                    <?php echo (!empty($post['gender']) && $post['gender'] == "female") ? 'checked': '';?>> Female
            </label>
        </div>

        <div class="col-sm-3">
            <label class="control-label">Age&nbsp;</label>
            <select class="form-control" name="age">
                <option value="">select your age</option>
            <?php if (!empty($post['age'])) :?>
                <?php for ($i = 1; $i < 50; $i++) :?>
                <option
                    value="<?php echo $i;?>"
                    <?php echo ($post['age'] == $i) ? 'selected="selected"' : '';?>>
                    <?php echo $i;?>
                </option>
                <?php endfor;?>
            <?php else : ?>
                <?php for ($i = 1; $i < 50; $i++) :?>
                <option value="<?php echo $i;?>"><?php echo $i;?></option>
                <?php endfor;?>
            <?php endif;?>
            </select>
        </div>

        <div class="col-sm-2">
            <input
                type="submit"
                class="btn btn-primary btn-lg pull-right"
                value="Filter">
        </div>
    </form>
    <br><br><br>
    <?php if ($usuarios) :?>
    <table class="table table-bordered">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Gender</th>
            <th>Age</th>
        </thead>
        <tbody>

            <?php foreach ($usuarios as $usuario) :?>
                <tr>
                    <td><a href="<?php echo $this->basePath()?>/foo/var/user/<?php echo $usuario['id'];?>"><?php echo $usuario['id']?></a></td>
                    <td><?php echo $usuario['firstName'] . " " . $usuario['lastName']?></td>
                    <td><?php echo $usuario['email']?></td>
                    <td><?php echo $usuario['gender']?></td>
                    <td><?php echo $usuario['age']?></td>
                </tr>
            <?php endforeach;?>

        </tbody>
    </table>
    <?php else :?>
        <h3 class="text-info">No se encontraron resultados! , por favor realice otra búsqueda</h3>
    <?php endif;?>
    <ul id="pagination-demo" class="pagination-sm"></ul>
</div>

<script type="text/javascript">
    $('#pagination-demo').twbsPagination({
        totalPages: <?php echo $cantPages?>,
        visiblePages: 3,
        href: '/foo/var/users/{{number}}',
        onPageClick: function (event, page) {
            $('#page-content').text('Page ' + page);
        }
    });
</script>
